compatibility_date = "2025-04-18"
kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]

[[ d1_databases ]]
binding = "DB"
database_name = "sonica-og-lasse-bryllup"
database_id = "02094b3b-051e-4ed9-833c-3203f91ae371"
migrations_dir = "migrations"